version: 1.0.{build}
image: Ubuntu

environment:
  nodejs_version: "18"

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки
  - npm run test

test_script:
  - npm run lint && npm test  # скрипт тестирования
